name: Electrod

on: push

jobs:
  binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            ocaml-compiler: 4.14.1
            dir: darwin/amd64
            file: electrod
            id: darwin-amd64
          - os: macos-14
            ocaml-compiler: 4.14.1
            dir: darwin/arm64
            file: electrod
            id: darwin-arm64
          - os: ubuntu-latest
            ocaml-compiler: 4.14.1
            dir: linux/amd64
            file: electrod
            id: linux-amd64
          - os: windows-latest
            ocaml-compiler: 4.14.1
            dir: windows/amd64
            file: electrod.exe
            id: windows-amd64
    steps:
      - name: checkout tree
        uses: actions/checkout@v4      
      - name: set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: |
            !electrod.opam.lock
            electrod.opam
      - name: Dependencies
        run: |
          opam install . --deps-only --with-test
          opam exec -- dune build 
          mkdir -p native/${{ matrix.dir }}
          cp electrod.exe native/${{ matrix.dir }}/${{ matrix.file }}
 
      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          path: native/
          name: ${{ matrix.id }}

  create-pr:
    needs: binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alloytools/org.alloytools.alloy'
          fetch-depth: 1
          path: 'org.alloytools.alloy'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: native/
          merge-multiple: true

      - name: Prepare binaries for PR
        run: |
          cd org.alloytools.alloy
          mkdir -p org.alloytools.pardinus.native/native/
          cp -rf ../native/* org.alloytools.pardinus.native/native
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add .
          git commit -m 'Update native binaries for electrod'
          git push origin HEAD:electrod-natives

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: org.alloytools.alloy
          branch: electrod-natives
          base: master
          title: 'Update native binaries for electrod'
          body: 'This PR includes updated native binaries for electrod.'